### ISSUE TITLE
SublimeText 3: Unable to type the '>' key

### ISSUE THREAD

**Issue by europasutton** [SublimeText/ColdFusion#135]
Installing the ColdFusion package disables the > key within SublimeText 3

**Comment by tdobeck17** [comment]
I know this is an old post, but how do you clone the development branch and reimport it?

I am new to coldfusion and could use all the help I can get! =)

**Comment by redtopia** [comment]
You want to use this plugin instead: https://github.com/jcberquist/sublimetext-cfml

**Comment by atuttle** [comment]
I use the plugin suggested by @redtopia, and it is pretty great. I might even go so far as to say we should deprecate this one and leave a message in the readme that people should go use that one.

**Comment by jimpriest** [comment]
It's already in the README:

This package is no longer maintained.
Please use jcberquist's excellent package: https://github.com/jcberquist/sublimetext-cfml
