### ISSUE TITLE
cannot close tags on Sublime Text 3

### ISSUE THREAD

**Issue by cfjesse** [SublimeText/ColdFusion#154]
I really like this plugin and I use it on Sublime Text 2 all the time.  But on Sublime Text 3 when I start for example a `<cfset` tag or any other tag it won't allow me to type the close for the tag `>` I am on windows 7 PC.  I am a Coldfusion and javascript developer. This issue is one of the reasons why I have not completely upgraded to ST3.

**Comment by atuttle** [comment]
Closing as a duplicate of #106

**Comment by deltaforce** [comment]
crikey 1 year and 8 months later, and this bug still exists.
The plugin is not really usable at all if you cannot close tags.

**Comment by atomi** [comment]
try https://github.com/jcberquist/sublimetext-cfml

**Comment by jevans-gp** [comment]
@deltaforce I would say this plugin is deprecated in favour of the one mentioned by @atomi

**Comment by deltaforce** [comment]
I have tried the one suggested and it is working fine thanks.
