### ISSUE TITLE
Syntax highlighting on script cfc's

### ISSUE THREAD

**Issue by GrahamFord** [SublimeText/ColdFusion#155]
I'm trying to move to ST3 from ST2 and I can't get the syntax highlighting to work for cfc's written entirely in cfscript. I'm running the "development" branch of the plugin and .cfm files are fine.

I figured it might be connected to the identified scopes. But having checked this, I always get the result "source.cfc.cfscript". How can I narrow down the cause of the issue?

**Comment by atomi** [comment]
Set your syntax to "ColdFusion Component", on the far right of your status bar.

**Comment by GrahamFord** [comment]
Yes, that was already set. I've spoken to a couple of colleagues and they say that with some files they see the colour highlighting, and with other cfc's they don't. Unfortunately they haven't been able to figure out what the similarity is with the files that end up looking like plain text.

**Comment by Panman8201** [comment]
The last commit dc81fc3 broke syntax highlighting for me as well. I'm on Mac OS X 10.9.5. Reverting fixed the issue. After following the [install / git checkout instructions](https://github.com/SublimeText/ColdFusion/tree/development#sublime-text-23), run the following in the same folder: `git revert dc81fc3 --no-edit --no-commit`

**Comment by atomi** [comment]
Yeah the ```<hidden>``` element was added in Build 3067 of Sublime Text which was only released a few days ago. I'll revert the change for now.

**Comment by atuttle** [comment]
IMO since using ST3 requires the development branch of this plugin, but ST3 offers both stable and unstable release branches, we need tagged development builds (to make them available for stable ST3 channel users) or just to ban ST3-unstable features from the development branch (new `development-st3-unstable` branch?)

**Comment by atomi** [comment]
sounds good to me

**Comment by GrahamFord** [comment]
Reverting out the <hidden> element has fixed things for me. Thanks for the help.
