### ISSUE TITLE
Unable to type ">"

### ISSUE THREAD

**Issue by siskulous** [SublimeText/ColdFusion#169]
The ">" character seems to be disabled when ColdFusion Markup is selected as the syntax in Sublime Text 2. Attempting to type it does absolutely nothing. Given how important this character is in CFML this is a major problem and makes the plugin unusable.

**Comment by atuttle** [comment]
Please see the discussion in #106 for how to resolve this. TL;DR: it's very likely that you're using the wrong branch for your Sublime version. (See the top of the project readme for details)
