### ISSUE TITLE
Syntax highlighting broken after update to newest build 3103

### ISSUE THREAD

**Issue by sebgmc** [SublimeText/ColdFusion#171]
Hi, is there someone actually doing some work on this plugin? The syntax highlighting was rather good until the latest build of Sublime 3 Text released this week. Now it is really FOOBAR. If I can help someone with something please let me know - using Sublime 3 Text a lot and with a BARFED syntax highlighter work is rather tedious and scary. Thingz that were correct now seem incorrect, but really aren't ;-)

**Comment by jevans-gp** [comment]
You might be best off moving to https://github.com/jcberquist/sublimetext-cfml.
I'm not sure if this package is being updated.

**Comment by atomi** [comment]
It's not.  @jcberquist has redone the highlighting using some new features added to ST3 and I believe he's replicated most if not all of the feauters of this plugin. It would be a good idea to add ask him to add his plugin to package control for Sublime Text 3.

**Comment by MattDMo** [comment]
Just to wrap this up, [CFML](https://packagecontrol.io/packages/CFML) is available on Package Control for ST3.
