### ISSUE TITLE
cfqueryparam attribute auto-complete

### ISSUE THREAD

**Issue by rsmolkin** [SublimeText/ColdFusion#176]
Is it possible after typing it cfqueryparam and hitting space to have it bring up a list of possible parameters such as value, CFSQLType, etc.?  Further, when tying in CFSQLType followed by equal and quote it would show a list of possible values for the types to pick from?

**Comment by jevans-gp** [comment]
This plugin has been deprecated, you should use https://github.com/jcberquist/sublimetext-cfml

**Comment by rsmolkin** [comment]
Thanks, do you know if that one works with VS Code?

**Comment by atuttle** [comment]
@rsmolkin there is a VSCode plugin for CFML but it is not _that_ one. It's not as feature-complete as https://github.com/jcberquist/sublimetext-cfml but VSCode itself has some pretty great features. Personally I'm really torn between the two. @jcberquist's CFML plugin for Sublime is awesome, and there's nothing offering as great support for CFML in VSCode, but VSCode is _just a little bit better_ for _almost_ everything else, I think.

VSCode CFML extensions: https://marketplace.visualstudio.com/search?term=cfml&target=VSCode&category=All%20categories&sortBy=Relevance
